// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAULKfP5AQw_11mkhubmcy_xvqcb2ngkqI',
    appId: '1:267819984321:web:0d25e51677e49373a1bb40',
    messagingSenderId: '267819984321',
    projectId: 'packup-4',
    authDomain: 'packup-4.firebaseapp.com',
    storageBucket: 'packup-4.appspot.com',
    measurementId: 'G-0CWDBLF1PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1OZZCzjtEJ5hEKzrigDayEpXIlN2KC8',
    appId: '1:267819984321:android:68856f491c67470ea1bb40',
    messagingSenderId: '267819984321',
    projectId: 'packup-4',
    storageBucket: 'packup-4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlKDLgPkAlVAYbdhJtQj0Ehpy5637G5rE',
    appId: '1:267819984321:ios:8abd39ceaedfe117a1bb40',
    messagingSenderId: '267819984321',
    projectId: 'packup-4',
    storageBucket: 'packup-4.appspot.com',
    iosBundleId: 'com.example.packUp',
  );

}